export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRDUCTS_SUCCESS = 'GET_PRDUCTS_SUCCESS';
export const GET_PRDUCTS_FAILURE = 'GET_PRDUCTS_FAILURE';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_FAILURE = 'REMOVE_PRODUCT_FAILURE';

export const GET_PRODUCTS_SELECT = 'GET_PRODUCTS_SELECT';
